version: '3'

networks:
  adop:
    driver: bridge

services:
  hub:
    container_name: selenium-hub
    restart: always
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
    expose:
      - "4444"
    networks:
      - adop

  node-firefox:
    container_name: selenium-node-firefox
    restart: always
    image: selenium/node-firefox:2.53.0
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-firefox.json"
      REMOTE_HOST: "http://selenium-node-firefox:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    networks:
      - adop
